version: '3'

services:

  app:
    container_name: app
    build:
      context: ./app
    image: wagnerrdemorais/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./app:/usr/src/app
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - node-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge