version: '3'

services:

  app:
    container_name: app
    image: wagnerrdemorais/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: wagnerrdemorais/db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    container_name: nginx
    image: wagnerrdemorais/nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge